global:
  scrape_interval: 15s

rule_files:
  - "rules.yml"

scrape_configs:
  - job_name: 'asg_webservers_hardware'
    ec2_sd_configs:
      - region: ap-southeast-2
        port: 9100
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        regex: job-portal-backend.*
        action: keep

# just_testing