- name: deploy backend
  hosts: all
  become: yes
  vars:
    ansible_connection: amazon.aws.aws_ssm
    ansible_aws_ssm_bucket_name: "job-portal-ssm-ansible-access"
    ansible_aws_ssm_region: "ap-southeast-2"
    image = "{{ ecr_registry }}/job_portal_backend:{{ image_tag }}"
  tasks: 
    - name: login aws ecr
      shell: |
        aws ecr get-login-password --region ap-southeast-2 | \
        docker login --username AWS --password-stdin {{ ecr_registry }}

    - name: pull image
      shell: |
        docker pull {{ image }}

    - name: stop old container
      shell: docker rm -f backend || true 

    - name: Run new container
      shell: |
        "docker run -d --name backend --restart always \
          -p 5000:5000 \
          --env-file /opt/app/.env \
          {{ image }}"
      

