- name: deploy backend
  hosts: all
  become: yes
  vars:
    ansible_connection: amazon.aws.aws_ssm
    ansible_aws_ssm_bucket_name: "job-portal-ssm-ansible-access"
    ansible_aws_ssm_region: "ap-southeast-2"
    image: "{{ ecr_registry }}/job_portal_backend:{{ image_tag }}"
    db_secrets: "{{ lookup('amazon.aws.aws_secret', 'dev/rds/db-credentials-v2') | from_json}}"
  tasks: 
    - name: login aws ecr
      shell: |
        aws ecr get-login-password --region ap-southeast-2 | \
        docker login --username AWS --password-stdin {{ ecr_registry }}

    - name: pull image
      shell: |
        docker pull {{ image }}

    - name: stop old container
      shell: docker rm -f backend || true 
    
    - name: ensure the path of saving secrets exist
      file:
        path:
        state: directory
        mode: '0755'
        owner: ubuntu
        group: ubuntu
      become: true

    #add .env and run new container
    - name: Fetch secrets and create .env file on the server
      copy:
        dest: /opt/app/.env
        mode: '0600'
        owner: ubuntu
        group: ubuntu
        content: |
          DB_HOST={{ db_secrets.host }}
          DB_USER={{ db_secrets.username }}
          DB_PASSWORD={{ db_secrets.password }}
          DB_NAME={{ db_secrets.dbname }}
      become: true
      
    - name: Run new container
      shell: |
        docker run -d --name backend --restart always \
          -p 5000:5000 \
          --env-file /opt/app/.env \
          {{ image }}

    # - name: Run backend container natively
    #   community.docker.docker_container:
    #     name: backend
    #     image: "{{ image }}"
    #     state: started
    #     restart_policy: always
    #     published_ports:
    #       - "5000:5000"
    #     env_file: /opt/app/.env
