name: Backend CI/CD
on:
  push:
    branches: [main]
    paths: ['backend/**']

env:
  AWS_REGION: ap-southeast-2
  ECR_REPO: job_portal_backend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write    # for OIDC keyless auth
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::698220459817:role/github-actions-deploy
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push
        working-directory: ./backend
        run: |
          IMAGE="${{ steps.ecr.outputs.registry }}/${{ env.ECR_REPO }}"
          docker build -t $IMAGE:${{ github.sha }} -t $IMAGE:latest .
          docker push $IMAGE:${{ github.sha }}
          docker push $IMAGE:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::698220459817:role/github-actions-deploy
          aws-region: ap-southeast-2

      - name: Install Ansible
        run: |
          pip install "ansible-core>=2.13.9" boto3
          ansible --version
          ansible-galaxy collection install amazon.aws

      - name: install aws ssm plugin
        run: | 
          curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
          sudo dpkg -i session-manager-plugin.deb

      - name: Run playbook
        working-directory: ./ansible
        run: |
          ansible-playbook -i inventory/aws_ec2.yml deploy.yml \
            -e "image_tag=${{ github.sha }}" \
            -e "ecr_registry=698220459817.dkr.ecr.ap-southeast-2.amazonaws.com"